### ISSUE TITLE
Unable to control anchor or engines

### ISSUE THREAD

**Issue by Tellik** [Aidanamite/Easy-Interactions#1]
I know the mod is partly working, and is loaded. I see the settings as well as when interacting with the steering wheel, it behaves as expected.

However, some of the controls for it don't. Steering left and right do work. Moving forward and backward do not work. As do neither of the shift/space to stop engines or drop anchor.

**Comment by Aidanamite** [comment]
I am not experiencing this issue myself. could you try to find some recreation conditions for this issue. it may be a conflict with another mod or an error occuring somewhere.

**Comment by Tellik** [comment]
My apologies. I completely misunderstood the intent of the mod. I was under the impression that the mod allowed control of engines/anchor/etc via the mod itself. You still need the appropriate research/blueprints/engine controls to allow the mod to function. Now that I have engine controls, at least I'm able to control the forward/backward directions.
